### PR TITLE
refactor: switch to titiler-dev

### PR DESCRIPTION
**Pull request by Thuhaa**
Thank you for submitting a pull request!

## Description
This PR fixes breaking changes brought about by upgrading from `titiler.undpgeohub.org` to `titiler-dev.undpgeohub.org`
The following changes have been made in geohub source code

1. The payload now uses `urls` key instead of `url` as was before
1. The mosaicjson `/create` endpoint was renamed to `/build`

### Type of Pull Request

* [ ] Adding a feature
* [ ] Fixing a bug
* [ ] Maintaining documents
* [ ] Adding tests
* [x] Others ()

### Verify the followings

* [x] Code is up-to-date with the `develop` branch
* [x] No build errors after `pnpm build`
* [x] No lint errors after `pnpm lint`
* [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`
* [x] Make sure all the existing features working well

### Changesets

* [ ] If your PR makes a change under `packages` folder that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

Refer to [CONTRIBUTING.MD](https://github.com/UNDP-Data/geohub/blob/develop/CONTRIBUTING.md) for more information.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1273640903) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by Thuhaa** [comment]
> @Thuhaa could you remove character of `B` from selectbox items? For new titiler, it will show like `Bb1`
> 
> https://github.com/UNDP-Data/geohub/blob/7b09c99be2655e82bbaeae8d1e89e198cd95cd2a/sites/geohub/src/components/pages/data/datasets/RasterBandSelectbox.svelte#L41-L43

@JinIgarashi  Please review

**Review by JinIgarashi — CHANGES_REQUESTED** [review]
could you add `is-capitalised` to class? so `b1` will be changed to `B1`

https://bulma.io/documentation/helpers/typography-helpers/#text-transformation

**Review by iferencik — APPROVED** [review]

**Comment by Thuhaa** [comment]
@JinIgarashi Please review and merge.

**Review by JinIgarashi — APPROVED** [review]

**Review by JinIgarashi — CHANGES_REQUESTED** [review]
please update CI for titiler.undpgeohub.org deployment. 

- delete k8s_titiler_deploy job, and switch name space of cogserver at k8s_cogserver_deploy
- use name space of titiler-dev when code was merged to develop branch, use name space of titiler when it is merged to main branch

**Pull request merged**
